// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://xgkrplrnxdzcjkobrced.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhna3JwbHJueGR6Y2prb2JyY2VkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwNTc3OTksImV4cCI6MjA4NzYzMzc5OX0.vk2-nx4v2p4VbokezCRlmdKUW7n4LY4ntGKc7_2IwK8";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);